---
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - action*
      - archive-cores
      - upload_final_status
      - xcore
    schedule:
      interval: weekly
    labels:
      - github-actions
      - dependencies
  - package-ecosystem: pip
    directories:
      - actions-cleanup-openstack-vms
    schedule:
      interval: weekly
