---
version: 2
updates:
  - package-ecosystem: github-actions
    permissions:
      pull-requests: read
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: github-actions
      include: scope
    labels:
      - github-actions
      - dependencies
