name: 'Basic Tests'
description: ''

inputs:
  name:
    required: true
    description: 'Name given to your image'
    default: 'default'
  docker_context:
    required: true
    description: 'Context for the docker build'
    default: '.'
  docker_file:
    required: true
    description: 'Path to the Dockerfile'
    default: 'Dockerfile'
  registry_url:
    required: false
    description: 'docker registry'
    default: 'ghcr.io'
  registry_username:
    required: false
    description: 'Registry username'
  registry_access_token:
    required: false
    description: 'Access token to access private repository'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildk
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - name: Login to Registry
      if: ${{ inputs.access_token }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_username || github.repository_owner }}
        password: ${{ inputs.access_token }}

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-{{ inputs.name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-{{ inputs.name }}-

    - name: Build and push ${{ inputs.name }}
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.docker_context }}/${{ inputs.docker_file }}
        tags: "ghcr.io/${{ github.repository }}/${{ inputs.name }}:${{ github.sha }}"
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

