name: 'Delete OpenStack VMs'
description: 'This action is to delete OpenStack VMs older than a certain period of time'

inputs:
  AGE_HOURS:
    description: 'the maximum age of the VM in hours; an older VM will be deleted'
    default: 6
    required: false
  CLOUD:
    description: the cloud provider
    required: false
    default: 'openstack'
  PASSWORD:
    description: 'the password of the OpenStack client'
    required: true
  AUTH_URL:
    description: 'the URL of the OpenStack client'
    required: true
  USERNAME:
    description: 'the username of the OpenStack client'
    required: true
  REGION:
    description: 'the region of the OpenStack client'
    required: true
  PROJECT_DOMAIN_ID:
    description: 'the project id of the OpenStack client'
    required: false
    default: 'default'
  USER_DOMAIN_ID:
    description: 'the user id of the OpenStack client'
    required: false
    default: 'default'
  PROJECT_NAME:
    description: 'the tenant of the OpenStack client'
    required: true
  PROJECT_ID:
    description: 'the tenant id of the OpenStack client'
    required: true
  ARTIFACTS_PASSWORD:
    required: true
  ARTIFACTS_USER:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install requirements
      shell: bash
      run: |-
        set -e
        sudo yum install -y epel-release
        sudo yum install -y https://rdoproject.org/repos/rdo-release.rpm
        sudo yum install -y python-openstackclient
      if: inputs.CLOUD == 'openstack'
    - name: Authenticate
      shell: bash
      run: |-
        echo "OS_PASSWORD=${{ inputs.PASSWORD }}" >> $GITHUB_ENV
        echo "OS_AUTH_URL=${{ inputs.AUTH_URL }}" >> $GITHUB_ENV
        echo "OS_USERNAME=${{ inputs.USERNAME }}" >> $GITHUB_ENV
        echo "OS_PROJECT_NAME=${{ inputs.PROJECT_NAME }}" >> $GITHUB_ENV
        echo "OS_PROJECT_ID=${{ inputs.PROJECT_ID }}" >> $GITHUB_ENV
        echo "OS_REGION=${{ inputs.REGION }}" >> $GITHUB_ENV
        echo "OS_PROJECT_DOMAIN_ID=${{ inputs.PROJECT_DOMAIN_ID }}" >> $GITHUB_ENV
        echo "OS_USER_DOMAIN_ID=${{ inputs.USER_DOMAIN_ID }}" >> $GITHUB_ENV
        echo "OS_IDENTITY_API_VERSION=3" >> $GITHUB_ENV
    - name: create artifacts folder
      id: temp-dir
      shell: bash
      run: |
        TEMP=$(mktemp -d)
        echo "Temp directory: ${TEMP}"
        echo "TEMP=$TEMP" >> $GITHUB_OUTPUT
    - name: Get list of VMs
      shell: bash
      run: echo "VM_LIST=$(openstack server list -f value -c ID)" >> $GITHUB_ENV
      id: vm_list
    - name: Delete old VMs
      shell: bash
      run: |-
        set -e
        delta=$(date -d "${{ inputs.AGE_HOURS }} hours ago" +%s)
        if [ -n "$VM_LIST" ]; then
          for vm in "$VM_LIST"; do
            creation_time=$(openstack server show -f value -c created "$vm")
            timestamp=$(date -d "$creation_time" +%s)
            if [ "$timestamp" -lt "$delta" ]; then
              openstack server delete --verbose "$vm" &>  ${{ steps.temp-dir.outputs.TEMP }}/.delete_status
            fi
          done
        else
          echo "No vm to delete" >> ${{ steps.temp-dir.outputs.TEMP }}/.delete_status
        fi
    - name: Upload logs to artifacts
      uses: scality/action-artifacts@v3
      if: always()
      with:
        method: upload
        url: https://artifacts.scality.net
        user: ${{ inputs.ARTIFACTS_USER }}
        password: ${{ inputs.ARTIFACTS_PASSWORD }}
        source:  ${{ steps.temp-dir.outputs.TEMP }}
