name: 'Delete OpenStack VMs'
description: 'This action is to delete OpenStack VMs older than a certain period of time'

inputs:
  AGE_HOURS:
    description: 'the maximum age of the VM in hours; an older VM will be deleted'
    default: 6
    required: false
  PASSWORD:
    description: 'the password of the OpenStack client'
    required: true
  AUTH_URL:
    description: 'the URL of the OpenStack client'
    required: true
  USERNAME:
    description: 'the username of the OpenStack client'
    required: true
  REGION:
    description: 'the region of the OpenStack client'
    required: true
  PROJECT_DOMAIN_ID:
    description: 'the project id of the OpenStack client'
    required: false
    default: 'default'
  USER_DOMAIN_ID:
    description: 'the user id of the OpenStack client'
    required: false
    default: 'default'
  PROJECT_NAME:
    description: 'the tenant of the OpenStack client'
    required: true
  PROJECT_ID:
    description: 'the tenant id of the OpenStack client'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
    - name: Install openstack client
      shell: bash
      run: |-
        pip install python-openstackclient
    - name: Authenticate
      shell: bash
      run: |-
        echo "OS_PASSWORD=${{ inputs.PASSWORD }}" >> $GITHUB_ENV
        echo "OS_AUTH_URL=${{ inputs.AUTH_URL }}" >> $GITHUB_ENV
        echo "OS_USERNAME=${{ inputs.USERNAME }}" >> $GITHUB_ENV
        echo "OS_PROJECT_NAME=${{ inputs.PROJECT_NAME }}" >> $GITHUB_ENV
        echo "OS_PROJECT_ID=${{ inputs.PROJECT_ID }}" >> $GITHUB_ENV
        echo "OS_REGION=${{ inputs.REGION }}" >> $GITHUB_ENV
        echo "OS_PROJECT_DOMAIN_ID=${{ inputs.PROJECT_DOMAIN_ID }}" >> $GITHUB_ENV
        echo "OS_USER_DOMAIN_ID=${{ inputs.USER_DOMAIN_ID }}" >> $GITHUB_ENV
        echo "OS_IDENTITY_API_VERSION=3" >> $GITHUB_ENV
        echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
    - name: Get list of VMs
      shell: bash
      run: |
        echo 'VM_LIST<<EOF' >> $GITHUB_ENV
        openstack server list -f value -c ID >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Delete old VMs
      shell: bash
      run: |-
        echo "### Cleanup Status" >> $GITHUB_STEP_SUMMARY
        delta=$(date -d "${{ inputs.AGE_HOURS }} hours ago" +%s)
        if [ -n "$VM_LIST" ]; then
          for vm in $VM_LIST; do
            creation_time=$(openstack server show -f value -c created "$vm")
            timestamp=$(date -d "$creation_time" +%s)
            if [ "$timestamp" -lt "$delta" ]; then
              set +e
              openstack server delete "$vm" --wait --verbose
              if [ $? -eq 0 ]; then
                echo "VM '$vm' deletion successful"
              else
                echo "VM '$vm' deletion failed"
              fi
              set -e
            fi
          done
          echo echo ":rocket: Cleanup of VMs older that ${{ inputs.AGE_HOURS }} hours successful" >> $GITHUB_STEP_SUMMARY
        else
          echo "No vm to delete" >> $GITHUB_STEP_SUMMARY
        fi
