name: artifacts-upload-final-status
description: 'upload to artifacts server a file .final_status with the appropriate final status'

inputs:
  ARTIFACTS_USER:
    description: The artifact user to upload the status
    required: true
  ARTIFACTS_PASSWORD:
    description: The artifact password to upload the status
    required: true
  JOBS_RESULTS:
    descript: Concatenation of jobs results
    required: true

runs:
  using: composite
  steps:
    - name: create artifacts folder
      id: temp-dir
      shell: bash
      run: |
        TEMP=$(mktemp -d)
        echo "Temp directory: ${TEMP}"
        echo "TEMP=$TEMP" >> $GITHUB_OUTPUT
    - name: write failed result
      shell: bash
      if: ${{ contains(inputs.JOBS_RESULTS, 'failed') || contains(inputs.JOBS_RESULTS, 'cancelled') || contains(inputs.JOBS_RESULTS, 'skipped') }}
      run: |
        echo -n "FAILED" > ${{ steps.temp-dir.outputs.TEMP }}/.final_status
    - name: write successful result
      shell: bash
      if: ${{ !contains(inputs.JOBS_RESULTS, 'failed') && !contains(inputs.JOBS_RESULTS, 'cancelled') && !contains(inputs.JOBS_RESULTS, 'skipped') }}
      run: |
        echo -n "SUCCESSFUL" > ${{ steps.temp-dir.outputs.TEMP }}/.final_status
    - name: upload file to artifacts
      uses: scality/action-artifacts@v3
      with:
        method: upload
        url: https://artifacts.scality.net
        user: ${{ inputs.ARTIFACTS_USER }}
        password: ${{ inputs.ARTIFACTS_PASSWORD }}
        source: ${{ steps.temp-dir.outputs.TEMP }}
