name: artifacts-upload-final-status
description: 'upload to artifacts server a file .final_status with the appropriate final status'

inputs:
  ARTIFACTS_USER:
    description: The artifact user to upload the status
    required: true
  ARTIFACTS_PASSWORD:
    description: The artifact password to upload the status
    required: true

runs:
  using: composite
  steps:
    - name: check required binaries
      shell: bash
      run: |
        gh --version
        wc --version
        mktemp --version
    - name: create artifacts folder
      id: temp-dir
      shell: bash
      run: |
        TEMP=$(mktemp -d)
        echo "Temp directory: ${TEMP}"
        echo "TEMP=$TEMP" >> $GITHUB_OUTPUT
    - name: get workflow status
      shell: bash
      id: nr-failed-jobs
      run: |
        nr_failed=$(gh -R ${{ github.repository }} \
          run view \
          --json="jobs" --jq='.jobs[] | select(.status == "completed" and .conclusion == "failure").conclusion' \
          ${{ github.run_id }} | wc -l)
        echo "failed jobs: ${nr_failed}"
        echo "NR_FAILED=${nr_failed}" >> ${GITHUB_OUTPUT}
    - name: write failed result
      shell: bash
      if: steps.nr-failed-jobs.outputs.NR_FAILED > 0
      run: |
        echo -n "FAILED" > ${{ steps.temp-dir.outputs.TEMP }}/.final_status
    - name: write successful result
      shell: bash
      if: steps.nr-failed-jobs.outputs.NR_FAILED == 0
      run: |
        echo -n "SUCCESSFUL" > ${{ steps.temp-dir.outputs.TEMP }}/.final_status
    - name: upload file to artifacts
      uses: scality/action-artifacts@v3
      with:
        method: upload
        url: https://artifacts.scality.net
        user: ${{ inputs.ARTIFACTS_USER }}
        password: ${{ inputs.ARTIFACTS_PASSWORD }}
        source: ${{ steps.temp-dir.outputs.TEMP }}
