name: "Delay job completion"
description: 'Sleep for a specified duration in order to delay completion of the job'

inputs:
  completion_delay_m:
    description: Completion delay (minutes)
    default: 30

runs:
  using: "composite"
  steps:
    - name: "Debug: Delay job completion"
      shell: bash
      run: |
        echo "Sleeping for ${{ inputs.completion_delay_m }} minutes.
        Delete the file '$GITHUB_WORKSPACE/timeout_date' to cancel.
        You can update that file with:
          date '+%s' --date='now + <X> minutes' > $GITHUB_WORKSPACE/timeout_date to change the delay."

        date '+%s' --date='now + ${{ inputs.completion_delay_m }} minutes' > $GITHUB_WORKSPACE/timeout_date
        while [ $(date '+%s') -lt $(cat $GITHUB_WORKSPACE/timeout_date 2>/dev/null || echo 0) ]; do sleep 5; done
