name: 'Test upload Dockerfile'

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions-docker-upload
        with:
          name: 'test'
          docker_context: './.github/docker'
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull "ghcr.io/${{ github.repository }}/test:${{ github.sha }}"
      - uses: ./upload_final_status
        if: always()
        id: artifacts
        with:
          ARTIFACTS_USER: ${{ secrets.ARTIFACTS_USER }}
          ARTIFACTS_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
      - name: print outputs
        run: |
          echo "Link: ${{ steps.artifacts.outputs.link }}"