---
name: openstack-cleanup

on:
  pull_request:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup OpenStack VMs
        uses: scality/actions/actions-cleanup-openstack-vms@${{ github.ref_name }}
        with:
          PASSWORD: ${{ secrets.OPENSTACK_PASSWORD }}
          AUTH_URL: ${{ secrets.OPENSTACK_AUTH_URL }}
          USERNAME: ${{ secrets.OPENSTACK_USERNAME }}
          REGION: ${{ secrets.OPENSTACK_REGION }}
          PROJECT_NAME: ${{ secrets.OPENSTACK_PROJECT_NAME }}
          PROJECT_ID: ${{ secrets.OPENSTACK_PROJECT_ID }}
