on:
  workflow_dispatch: {}
  push: {}


jobs:
  ssh:
    runs-on:
    - self-hosted
    - centos7
    - large
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: ssh
      uses: ./action-ssh-to-runner
      with:
        sudo: true
        tmate-server-host: "${{ secrets.TMATE_SERVER_HOST }}"
        tmate-server-port: "${{ secrets.TMATE_SERVER_PORT }}"
        tmate-server-rsa-fingerprint: "${{ secrets.TMATE_SERVER_RSA_FINGERPRINT }}"
        tmate-server-ed25519-fingerprint: "${{ secrets.TMATE_SERVER_ED25519_FINGERPRINT }}"
