on:
  workflow_dispatch:
    inputs:
      runner:
        description: Type of runner
        required: false
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - redhat8
          - rocky8
          - aws
          - gcloud

name: ssh to runner

jobs:
  ssh:
    strategy:
      fail-fast: true
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ssh
      uses: ./action-ssh-to-runner
      with:
        tmate-server-host: "${{ secrets.TMATE_SERVER_HOST }}"
        tmate-server-port: "${{ secrets.TMATE_SERVER_PORT }}"
        tmate-server-rsa-fingerprint: "${{ secrets.TMATE_SERVER_RSA_FINGERPRINT }}"
        tmate-server-ed25519-fingerprint: "${{ secrets.TMATE_SERVER_ED25519_FINGERPRINT }}"
